version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: Blog
      POSTGRES_USER: Blog
      POSTGRES_DB: Blog
      POSTGRES_INITDB_ARGS: '-A md5'
    ports: 
      - 5432

volumes:
  postgres_data:

  